### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by cpkkcb** [netxfly/x-crack#15]
./x-crack_darwin_amd64 scan -u /Desktop/fuzzDicts/port_pass/smb_pass.txt -p  Desktop/fuzzDicts/port_pass/smb_pass.txt  -i ip.txt         
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
x-crack/util.ReadIpList(0x7ffeefbffbe7, 0x6, 0x0, 0x0, 0x0)
	/opt/data/code/golang/src/x-crack/util/file.go:57 +0x823
x-crack/util.Scan(0xc0000c0c60, 0x10100, 0xc0000c0c60)
	/opt/data/code/golang/src/x-crack/util/task.go:210 +0x28d
github.com/urfave/cli.HandleAction(0x168a100, 0x17bc070, 0xc0000c0c60, 0xc0000a6600, 0x0)
	/opt/data/code/golang/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.Command.Run(0x1790b9b, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x179ef44, 0x1c, 0x0, ...)
	/opt/data/code/golang/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x991
github.com/urfave/cli.(*App).Run(0xc0002fa680, 0xc0000ae000, 0x8, 0x8, 0x0, 0x0)
	/opt/data/code/golang/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x6ab
main.main()
	/opt/data/code/golang/src/x-crack/x-crack.go:50 +0x24e

**Comment by netxfly** [comment]
格式不对，看下格式吧
