### ISSUE TITLE
能不能针对同一个ip同一个服务优化扫描

### ISSUE THREAD

**Issue by YouZhengChuan** [netxfly/x-crack#3]
如果针对同一个ip的同一个服务，一个用户名，有很多个密码，目前的逻辑开启扫描之后，需要等到所有的密码扫描任务结束。

能不能在其中一个密码扫描成功之后，其他密码的扫描任务都停止？

**Comment by netxfly** [comment]
现在的策略是会按次数建立扫描任务，同一批是并行的协程，之间没有通讯机制，所以同一批中，虽然有扫到结果的，也不会通知其他的协程停下来。但是这批协程结束后就不会再去扫描了。
