### ISSUE TITLE
建议增加功能和改进

### ISSUE THREAD

**Issue by 930201676** [netxfly/x-crack#4]
1. 希望增加一个svn爆破功能，很多情况还是有大部人在使用svn服务。

2. 希望能改进保存功能或其他方法保存结果【在使用中一般都会选择速度优先，在大范围测试中不考虑线程和机器配置（默认线程）往往会跑着跑着就机器就爆掉了。已经爆破出来的结果也没有及时保存。】

**Comment by netxfly** [comment]
OK，我记录下，回头加一下SVN破解及实时保存结果的功能。
