### ISSUE TITLE
go: golang.org/x/sys@v0.0.0-20180905080454-ebe1bf3edb33: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: connect: connection refused)

### ISSUE THREAD

**Issue by wenchangming211** [netxfly/x-crack#7]
请问这个地址连接不上如何解决，谢谢，
go: golang.org/x/sys@v0.0.0-20180905080454-ebe1bf3edb33: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: connect: connection refused)

**Comment by netxfly** [comment]
这个是被墙了，用代理或者墙外的机器去拉这个包
