### ISSUE TITLE
gosnmp包报错

### ISSUE THREAD

**Issue by wenchangming211** [netxfly/x-crack#8]
o: extracting cloud.google.com/go v0.36.0
go: extracting golang.org/x/sys v0.0.0-20181029174526-d69651ed3497
build command-line-arguments: cannot load github.com/soniah/gosnmp: zip for github.com/soniah/gosnmp@v0.0.0-20190109014816-922fbec967ca has unexpected file github.com/soniah/gosnmp@v0.0.0-0.20190109014816-922fbec967ca/.gitignore
mv: cannot stat `x-crack': No such file or directory
go: downloading github.com/soniah/gosnmp v0.0.0-20190109014816-922fbec967ca
build command-line-arguments: cannot load github.com/soniah/gosnmp: zip for github.com/soniah/gosnmp@v0.0.0-20190109014816-922fbec967ca has unexpected file github.com/soniah/gosnmp@v0.0.0-0.20190109014816-922fbec967ca/.gitignore
mv: cannot stat `x-crack': No such file or directory
go: downloading github.com/soniah/gosnmp v0.0.0-20190109014816-922fbec967ca
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: extracting github.com/konsorten/go-windows-terminal-sequences v1.0.1
build command-line-arguments: cannot load github.com/soniah/gosnmp: zip for github.com/soniah/gosnmp@v0.0.0-20190109014816-922fbec967ca has unexpected file github.com/soniah/gosnmp@v0.0.0-0.20190109014816-922fbec967ca/.gitignore
mv: cannot stat `x-crack.exe': No such file or directory
go: downloading github.com/soniah/gosnmp v0.0.0-20190109014816-922fbec967ca
build command-line-arguments: cannot load github.com/soniah/gosnmp: zip for github.com/soniah/gosnmp@v0.0.0-20190109014816-922fbec967ca has unexpected file github.com/soniah/gosnmp@v0.0.0-0.20190109014816-922fbec967ca/.gitignore
[root@localhost x-crack-master]#

**Comment by netxfly** [comment]
release中有编译好的二进制文件
