### ISSUE TITLE
麻烦指导一下，怎么能跑起来，谢谢

### ISSUE THREAD

**Issue by wenchangming211** [netxfly/x-crack#9]
[root@localhost x-crack-master]# go test -v plugins/ssh_test.go
go: downloading github.com/soniah/gosnmp v0.0.0-20190109014816-922fbec967ca
# command-line-arguments
/usr/local/go/src/x-crack-master/models/cache.go:28:2: non-standard import "github.com/patrickmn/go-cache" in standard package "x-crack/models"
FAIL	command-line-arguments [setup failed]
[root@localhost x-crack-master]#

**Comment by netxfly** [comment]
go get 好依赖包后直接go build x_crack.go，或者用go mod tidy自动下载依赖包。

如果暂时搞不定，可以去release中下载编译好的二进制文件

**Comment by wenchangming211** [comment]
请问您扣扣或者微信多少


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: netxfly <notifications@github.com>
发送时间: 2019年6月11日 10:31
收件人: netxfly/x-crack <x-crack@noreply.github.com>
抄送: wenchangming211 <2568376869@qq.com>, Author <author@noreply.github.com>
主题: 回复：[netxfly/x-crack] 麻烦指导一下，怎么能跑起来，谢谢 (#9)




Closed #9.

**Comment by wenchangming211** [comment]
我测试了一下创建了一个普通用户，用户名和密码一样，但是没有检测出来


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: netxfly <notifications@github.com>
发送时间: 2019年6月11日 10:31
收件人: netxfly/x-crack <x-crack@noreply.github.com>
抄送: wenchangming211 <2568376869@qq.com>, Author <author@noreply.github.com>
主题: 回复：[netxfly/x-crack] 麻烦指导一下，怎么能跑起来，谢谢 (#9)




Closed #9.
